### ISSUE TITLE
Behind proxy can't download

### ISSUE THREAD

**Issue by AdrianoCahete** [makovich/google-fonts-offline#2]
When you are behind a proxy, you can't download:

```
C:\>goofoffline "http://fonts.googleapis.com/css?family=Ubuntu:
400,700italic,700,500italic,500,400italic,300italic,300"
Mimics to http://fonts.googleapis.com/css?family=Ubuntu:400,700italic,700,500italic,500,400italic,300italic,300...
Request error: connect ETIMEDOUT
Composing CSS file...
Done!
```

It's showing done, but don't download anything.
Others packages have proxy settings, can we have this here too?

**Comment by makovich** [comment]
Can you give me some examples of other packages. And of course feel free to make a pull request! ;)

**Comment by NanoCahete** [comment]
If i remember correctly, Gulp has (https://www.npmjs.com/package/gulp) his settings. And i dind't have that expertise. :(

**Comment by makovich** [comment]
Did you try something as described here http://wil.boayue.com/blog/2013/06/14/using-npm-behind-a-proxy/?
