### ISSUE TITLE
Missing eot 

### ISSUE THREAD

**Issue by talelamira** [makovich/google-fonts-offline#8]
In the generated fonts.css I have this:
```
@font-face {
    font-family: 'Imprima';
    font-style: normal;
    font-weight: 400;
    src: url(Imprima_400_normal.eot); /* {{embedded-opentype-gf-url}} */
    src: local('☺'),
        url(Imprima_400_normal.eot?#iefix) format('embedded-opentype'), /* {{embedded-opentype-gf-url}} */
        url(Imprima_400_normal.woff) format('woff'), /* http://fonts.gstatic.com/s/imprima/v5/Lw4J4XiH21tNmX0DzARuSA.woff */
        url(Imprima_400_normal.ttf) format('truetype'), /* http://fonts.gstatic.com/s/imprima/v5/2EXx4nGYK3bgPf_CMqSI6ALUuEpTyoUstqEm5AMlJo4.ttf */
        url(Imprima_400_normal.svg#Imprima_400_normal) format('svg'); /* http://fonts.gstatic.com/l/font?kit=9BZZnfydqHefT-T0DXwEUA&skey=29732b71f07bec76&v=v5#Imprima */
}
```
And I have the following error:

> ./src/fonts/fonts.css
> Module not found: Can't resolve './Imprima_400_normal.eot' in '~\src\fonts'

As a workaround I deleted the two references to the missing file, and it works

**Comment by 06chaynes** [comment]
I can confirm I have this exact issue as well, fix worked as well but I did choose to download those files manually for now. Luckily I am only using this for a single font.

**Comment by stephlocke** [comment]
I had this too, will use the workaround

**Comment by makovich** [comment]
Hi gentlemen! That is absolute truth! I'm not sure that I've fully fixed this issue with EOT but as it happens to say: "It works on my machine!" :0) I think that the best backup strategy is to download fonts manually anyway.
