### ISSUE TITLE
'subset' is not recognized as an internal or external command.

### ISSUE THREAD

**Issue by saaiful** [makovich/google-fonts-offline#9]
My font configuration has subset and it's not working perfectly.
http://fonts.googleapis.com/css?family=Hind+Siliguri:400,300,500,600,700&subset=bengali,latin

**Comment by makovich** [comment]
Hello and thank you for letting me know! My best guess is that Google Fonts have no all the "precalculated" font formats. EOT at least have no all modifications from your URL. However it might be some other nasties which probably already fixed.
